import React from 'react';
const pct = (v) => v == null ? 'Not available' : `${Math.round(Number(v) * 100)}%`;
export default function RagQualityGate({ evaluation, citations = [] }) {
  if (!evaluation) return null;
  const evidenceCoverage = evaluation.retrieved_evidence_coverage ?? evaluation.citation_coverage;
  const values = [evaluation.groundedness_score, evaluation.semantic_similarity_score, evaluation.answer_relevance_score, evidenceCoverage].filter((v) => v != null);
  const gate = values.some((v) => Number(v) < .4) ? 'BLOCK' : values.some((v) => Number(v) < .6) ? 'REVIEW' : 'PASS';
  return <div style={{ marginTop: 14, padding: 14, border: '1px solid var(--border)', borderRadius: 6, background: 'var(--surface-inset)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, marginBottom: 10 }}><strong style={{ fontSize: 13 }}>RAG Quality Gate</strong><span style={{ fontSize: 11, fontWeight: 700, color: gate === 'PASS' ? 'var(--success)' : gate === 'REVIEW' ? 'var(--warning)' : 'var(--error)' }}>{evaluation.quality_gate || gate}</span></div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '7px 14px', fontSize: 12 }}><span>lexical_groundedness: <b>{pct(evaluation.groundedness_score)}</b></span><span>embedding_similarity: <b>{pct(evaluation.semantic_similarity_score)}</b></span><span>lexical_answer_relevance: <b>{pct(evaluation.answer_relevance_score)}</b></span><span>retrieved_evidence_coverage: <b>{pct(evidenceCoverage)}</b></span><span>llm_judge: <b>{evaluation.llm_judge_score == null ? 'Not run' : pct(evaluation.llm_judge_score)}</b></span><span>Method: <b>{evaluation.evaluator_method || 'Not available'}</b></span></div>{evaluation.reason && <div style={{ marginTop: 9, fontSize: 12 }}>Reason: {evaluation.reason}</div>}{citations?.length > 0 && <div style={{ marginTop: 9, fontSize: 12 }}>Retrieved Evidence: {citations.length} source{citations.length === 1 ? '' : 's'} retrieved</div>}</div>;
}
